### PR TITLE
fix: better error message if react-scripts dependency cannot be found

### LINKED ISSUE #1561: Could not inject "optionsFactory". Inner error: Cannot find module 'react-scripts/package.json'
### Summary

I just installed stryker globally and run `stryker init`. I answered the following:

> ? Do you want to install Stryker locally? yarn
> ? Are you using one of these frameworks? Then select a preset configuration. react
> ? Is your project a JSX project or a TSX project? JSX
> ? Which package manager do you want to use? yarn

By the way, I loved the `|STRYKER| ~control the mutants~` output.

Then I run `stryker run` and I got the following output
```
$ stryker run
16:27:33 (23309) INFO ConfigReader Using stryker.conf.js in the current working directory.
Could not inject "optionsFactory". Inner error: Cannot find module 'react-scripts/package.json'
```

Any help would be really appreciated. Looking forward to using this tool.

PS. Very clean and thorough issue template 👏 

### Stryker config

```js
module.exports = function (config) {
  config.set({
    mutate: ['src/**/*.js?(x)', '!src/**/*@(.test|.spec|Spec).js?(x)'],
    mutator: 'javascript',
    testRunner: 'jest',
    reporters: ['progress', 'clear-text', 'html'],
    coverageAnalysis: 'off',
    jest: {
      projectType: 'react'
    }
  })
}
```

### Stryker environment

```
├─┬ @stryker-mutator/core@2.0.0
│ ├─┬ @stryker-mutator/api@2.0.0
│ ├── @stryker-mutator/util@2.0.0
├─┬ @stryker-mutator/html-reporter@2.0.0
│ ├── @stryker-mutator/api@2.0.0 deduped
│ ├── @stryker-mutator/util@2.0.0 deduped
├─┬ @stryker-mutator/javascript-mutator@2.0.0
│ ├── @stryker-mutator/api@2.0.0 deduped
├─┬ @stryker-mutator/jest-runner@2.0.0
│ ├── @stryker-mutator/api@2.0.0 deduped
```

```
├── jest@23.6.0
├── jest-junit@6.3.0
```

### Test runner environment

```
# Test command
"test": "yarn lint && yarn test:unit",
"test:unit": "jest --coverage",
"watch": "jest --watch --verbose"
```

```js
const ignorePatterns = ['<rootDir>/.build/', '<rootDir>/node_modules/']

module.exports = {
  setupFiles: ['./jest.setup.js'],
  moduleNameMapper: {
    '\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$': '<rootDir>/client/__mocks__/fileMock.js',
    '\\.(css|css\\?raw)$': 'identity-obj-proxy'
  },
  reporters: [
    'default',
    ['jest-junit', {
      outputDirectory: '.build/test-results',
      ancestorSeparator: ' › ',
      classNameTemplate: '{classname}',
      suiteNameTemplate: '{filepath}',
      titleTemplate: '{title}'
    }]
  ],
  coverageDirectory: '.build/coverage-results',
  coverageReporters: [
    'cobertura',
    'text-summary',
    'lcov'
  ],
  testPathIgnorePatterns: ignorePatterns,
  modulePathIgnorePatterns: ignorePatterns,
  testURL: 'http://localhost/'
}

```

### Your Environment

| software         | version(s)
| ---------------- | -------  
| node             | v8.11.4
| npm              | 6.9.0
| Operating System | macOS Mojave 10.14

### Add stryker.log

```
16:44:33 (23803) INFO ConfigReader Using stryker.conf.js in the current working directory.
16:44:33 (23803) DEBUG ConfigReader Loading config stryker.conf.js
16:44:33 (23803) DEBUG PluginLoader Loading @stryker-mutator/* from /Users/path-to-my-repo/node_modules/@stryker-mutator
16:44:33 (23803) DEBUG PluginLoader Loading plugin "/Users/path-to-my-repo/node_modules/@stryker-mutator/html-reporter" (matched with expression @stryker-mutator/*)
16:44:33 (23803) DEBUG PluginLoader Loading plugin "/Users/path-to-my-repo/node_modules/@stryker-mutator/javascript-mutator" (matched with expression @stryker-mutator/*)
16:44:33 (23803) DEBUG PluginLoader Loading plugin "/Users/path-to-my-repo/node_modules/@stryker-mutator/jest-runner" (matched with expression @stryker-mutator/*)
16:44:33 (23803) DEBUG PluginLoader Loading plugins /Users/path-to-my-repo/node_modules/@stryker-mutator/html-reporter
16:44:33 (23803) DEBUG PluginLoader Loading plugins /Users/path-to-my-repo/node_modules/@stryker-mutator/javascript-mutator
16:44:33 (23803) DEBUG PluginLoader Loading plugins /Users/path-to-my-repo/node_modules/@stryker-mutator/jest-runner
16:44:33 (23803) DEBUG PluginLoader Loading plugins /Users/path-to-my-repo/node_modules/@stryker-mutator/core/src/reporters/index.js
```

### PR DESCRIPTION
**Pull request by marcelvdh**
Fixes #1561

### CODE REVIEW

File: packages/jest-runner/src/configLoaders/ReactScriptsJestConfigLoader.ts [hunk 1]
```diff
@@ -13,16 +13,30 @@ export default class ReactScriptsJestConfigLoader implements JestConfigLoader {
...
+      jestConfiguration.testEnvironment = 'jsdom';
 
-    return jestConfiguration;
+      return jestConfiguration;
+    }
+    catch (e) {
+      if (this.isNodeErrnoException(e) && e.code === 'MODULE_NOT_FOUND') {
+        throw Error('Unable to locate package react-scripts. ' +
+          'This package is required when projectType is set to "react".');
+      } else {
```
Comment (kmdrGroch) [inline packages/jest-runner/src/configLoaders/ReactScriptsJestConfigLoader.ts]: `else` is not necessary here since `throw` works +- like `return`

File: packages/jest-runner/src/configLoaders/ReactScriptsTSJestConfigLoader.ts [hunk 2]
```diff
@@ -13,16 +13,30 @@ export default class ReactScriptsTSJestConfigLoader implements JestConfigLoader
...
+      jestConfiguration.testEnvironment = 'jsdom';
 
-    return jestConfiguration;
+      return jestConfiguration;
+    }
+    catch (e) {
+      if (this.isNodeErrnoException(e) && e.code === 'MODULE_NOT_FOUND') {
+        throw Error('Unable to locate package react-scripts-ts. ' +
+          'This package is required when projectType is set to "react-ts".');
+      } else {
```
Comment (kmdrGroch) [inline packages/jest-runner/src/configLoaders/ReactScriptsTSJestConfigLoader.ts]: `else` is not necessary here

File: packages/jest-runner/src/configLoaders/ReactScriptsJestConfigLoader.ts (hunk 1 above)
Comment (marcelvdh) [reply packages/jest-runner/src/configLoaders/ReactScriptsJestConfigLoader.ts]: Done

File: packages/jest-runner/src/configLoaders/ReactScriptsTSJestConfigLoader.ts (hunk 2 above)
Comment (marcelvdh) [reply packages/jest-runner/src/configLoaders/ReactScriptsTSJestConfigLoader.ts]: Done

**Comment by kmdrGroch** [comment]
looks good to me, i dunno why it had error in E2E tho

**Comment by marcelvdh** [comment]
@kmdrGroch 

Thanks for your feedback.

Build Server output:

>20:40:13 (7910) ERROR StrykerCli an error occurred Error: Error: MODULE_NOT_FOUND >(undefined) Error: Cannot find module '@angular/cli/package'

**Comment by kmdrGroch** [comment]
@marcelvdh I saw it. Strange thing is that your previous build had passed, and in the next (where you changed only comments) didn't. So I assume it's just a one-time error.

**Comment by marcelvdh** [comment]
> @marcelvdh I saw it. Strange thing is that your previous build had passed, and in the next (where you changed only comments) didn't. So I assume it's just a one-time error.

@kmdrGroch I started the build again it passed this time.

**Comment by nicojs** [comment]
I've added tests for the new messages. Wil merge when green. Thanks @marcelvdh and @kmdrGroch

**Comment by kmdrGroch** [comment]
@nicojs greeen! :D

**Comment by nicojs** [comment]
Awesome, thanks for the work @marcelvdh
