### PR TITLE
fix(sandbox): Prevent hanging child processes

### LINKED ISSUE #396: Stryker not closing correctly with low number of mutants
The latest and greatest Stryker v0.10.2 doesn't seem to close correctly with a low number of mutants. See this example repo:

https://github.com/nicojs/stryker-typescript-issue394

It first creates way too many sandboxes and later only closes the one that actually ran tests (which is 1):

```bash
[2017-09-27 08:51:04.545] [INFO] SandboxCoordinator - Creating 7 test runners (based on CPU count)
[2017-09-27 08:51:04.549] [DEBUG] Sandbox - Creating a sandbox for files in C:\z\github\nicojs\stryker-typescript-issue394\.stryker-tmp\sandbox5322435
[2017-09-27 08:51:04.551] [DEBUG] Sandbox - Creating a sandbox for files in C:\z\github\nicojs\stryker-typescript-issue394\.stryker-tmp\sandbox6179253
[2017-09-27 08:51:04.552] [DEBUG] Sandbox - Creating a sandbox for files in C:\z\github\nicojs\stryker-typescript-issue394\.stryker-tmp\sandbox7459993
[2017-09-27 08:51:04.553] [DEBUG] Sandbox - Creating a sandbox for files in C:\z\github\nicojs\stryker-typescript-issue394\.stryker-tmp\sandbox1805168
[2017-09-27 08:51:04.554] [DEBUG] Sandbox - Creating a sandbox for files in C:\z\github\nicojs\stryker-typescript-issue394\.stryker-tmp\sandbox7940097
[2017-09-27 08:51:04.555] [DEBUG] Sandbox - Creating a sandbox for files in C:\z\github\nicojs\stryker-typescript-issue394\.stryker-tmp\sandbox2232950
[2017-09-27 08:51:04.556] [DEBUG] Sandbox - Creating a sandbox for files in C:\z\github\nicojs\stryker-typescript-issue394\.stryker-tmp\sandbox9039988
[2017-09-27 08:51:04.560] [DEBUG] Sandbox - Creating test runner 0 using settings {port: 9234}
[2017-09-27 08:51:04.566] [DEBUG] Sandbox - Creating test runner 1 using settings {port: 9235}
[2017-09-27 08:51:04.571] [DEBUG] Sandbox - Creating test runner 2 using settings {port: 9236}
[2017-09-27 08:51:04.575] [DEBUG] Sandbox - Creating test runner 3 using settings {port: 9237}
[2017-09-27 08:51:04.580] [DEBUG] Sandbox - Creating test runner 4 using settings {port: 9238}
[2017-09-27 08:51:04.585] [DEBUG] Sandbox - Creating test runner 5 using settings {port: 9239}
[2017-09-27 08:51:04.591] [DEBUG] Sandbox - Creating test runner 6 using settings {port: 9240}
```

### PR DESCRIPTION
**Pull request by nicojs**
* Rename `SandboxCoordinator` -> `SandboxPool`
* Make sure newly created sandboxes are also disposed if the SandboxPool is already disposed

fixes #396

### CODE REVIEW

**Comment by nicojs** [comment]
BTW this also fixes our flaky integration tests

File: packages/stryker/src/Sandbox.ts [hunk 1]
```diff
@@ -46,11 +46,17 @@ export default class Sandbox {
...
-  public async initialize(): Promise<void> {
+  private async initialize(): Promise<void> {
     await this.fillSandbox();
     return this.initializeTestRunner();
   }
 
+  public static create(options: Config, index: number, files: ReadonlyArray<File>, testFramework: TestFramework | null, coverageInstrumenter: CoverageInstrumenter | null)
+    : Promise<Sandbox> {
+    const sandbox = new Sandbox(options, index, files, testFramework, coverageInstrumenter);
+    return sandbox.initialize().then(() => sandbox);
```
Comment (simondel) [inline packages/stryker/src/Sandbox.ts]: So, this returns a promise that so when initialize completes, the sandbox object will be returned?

Comment (nicojs) [reply packages/stryker/src/Sandbox.ts]: Yes. It was always required to call `initialize` after creating a sandbox. This way, there is no way you can forget doing it.

**Comment by simondel** [comment]
Epic! You figured out the issue 🥇
