### PR TITLE
fix(core): fix "too many open files"

### LINKED ISSUE #1227: Analysis crashes with 'too many open files'
### Summary

When running stryker on my day job project, I get a "too many open files error"
This is a project using Flow (version 0.65). I have tested the config on a small hello world project, it worked fine.

### Stryker config

```js
module.exports = function(config){
  config.set({
      logLevel: 'debug',
      mutator: "javascript",
      packageManager: "yarn",
      reporters: ["html", "clear-text", "progress"],
      testRunner: "jest",
      transpilers: [],
      coverageAnalysis: "off",
      files: [
        "./subproject/**/*.*",
      ],
      mutate: [
        "./subproject/**/*.js",
        '!**/*.spec.js',
        '!**/*.test.js',
      ],
      jest: {
        config: require('./.jest.stryker.json'),
      },
  });
}
```

### Stryker environment

```
├─┬ stryker@0.30.0
│ ├── @stryker-mutator/util@0.0.1
├─┬ stryker-api@0.21.4
├─┬ stryker-html-reporter@0.16.5
│ ├── @stryker-mutator/util@0.0.1 deduped
├─┬ stryker-javascript-mutator@0.11.2
├─┬ stryker-jest-runner@1.2.4 
```

```
"jest": "^23.6.0",
```

### Your Environment

| software         | version(s)
| ---------------- | -------  
| node             | 8.10.0
| yarn              | 1.5.1
| Operating System | 
MacOs 10.14

### Add stryker.log

[stryker.too_many_files.log](https://github.com/stryker-mutator/stryker/files/2545100/stryker.too_many_files.log)

### PR DESCRIPTION
**Pull request by nicojs**
Fixes "too many open files" issue by limiting the number of concurrent file IO to 256

Fixes #1227

### CODE REVIEW

File: packages/core/src/input/InputFileResolver.ts [hunk 1]
```diff
@@ -157,13 +159,20 @@ export default class InputFileResolver {
...
+        toArray()
+      )
+      .toPromise();
+    return files;
   }
 
   private async readFile(fileName: string): Promise<File | null> {
     try {
-      const content = await fs.readFile(fileName);
+      const p = fs.promises.readFile(fileName);
```
Comment (kmdrGroch) [inline packages/core/src/input/InputFileResolver.ts:174]: is there a reason for making it 2 liner?

Comment (nicojs) [reply packages/core/src/input/InputFileResolver.ts:174]: yeah, was debugging it earlier (🦸‍♀️hacker by night). Removing it 👍

Comment (nicojs) [reply packages/core/src/input/InputFileResolver.ts]: Fixed ✅
