### PR TITLE
 fix(webpack-transpiler): Correctly use in-memory files

### LINKED ISSUE #597: Module not found error when using the stryker-webpack-transpiler
### Summary

The InputFileSystem of the Stryker webpack transpiler does not mix-and-match correctly. 

See this line:
https://github.com/stryker-mutator/stryker/blob/9b86254265f04bf5793945f1798a326a62f996b5/packages/stryker-webpack-transpiler/src/fs/InputFileSystem.ts#L38-L40

When we create the path in-memory and later read from the directory we end up communicating less directories than exist on disk.

More info including reproduction can be found here: https://github.com/nicojs/angular-stryker-example/issues/1

### PR DESCRIPTION
**Pull request by nicojs**
Correctly use in-memory files. Instead of caching them ourselves, extend webpack's `CachedInputFileSystem` and rely on that for caching files. Still use memory-FS to load the in-memory files.

One downside is that I had to set the typescript target to "es2015", which means we have to drop support for node-4 on the stryker-webpack-transpiler package.

Fixes #597

### CODE REVIEW

File: packages/stryker-webpack-transpiler/src/fs/InputFileSystem.ts [hunk 1]
```diff
@@ -1,125 +1,66 @@
...
-
-  public readlink(path: any, callback?: any) {
-    this.memoryFS.readlink(path, (err: Error, file: string) => {
-      if (err) {
-        fs.readlink(path, callback);
-      }
-      else {
-        callback(err, file);
+  public readFile(...args: any[]) {
+    const memoryFSArgs = args.filter((_, index) => index !== args.length - 1);
```
Comment (simondel) [inline packages/stryker-webpack-transpiler/src/fs/InputFileSystem.ts]: Why is this last item of the args so important?

File: packages/stryker-webpack-transpiler/src/fs/InputFileSystem.ts [hunk 2]
```diff
@@ -1,125 +1,66 @@
...
+    memoryFSArgs.push((error: NodeJS.ErrnoException, content: any) => {
+      if (error) {
+        super.readFile.apply(this, args);
+      } else {
+        args.find((_, index) => index === args.length - 1)(error, content);
```
Comment (simondel) [inline packages/stryker-webpack-transpiler/src/fs/InputFileSystem.ts]: Cant we use `args[args.length - 1]`?

File: packages/stryker-webpack-transpiler/src/fs/InputFileSystem.ts (hunk 1 above)
Comment (simondel) [reply packages/stryker-webpack-transpiler/src/fs/InputFileSystem.ts]: Can't we use `args.slice(0, args.length -1);`

**Comment by nicojs** [comment]
Great review. Didn't know what I was thinking, fixing that tomorrow

**Comment by Archcry** [comment]
Hmm, breaking compatibility with node4 seems reasonable since its LTS will end in April.

File: packages/stryker-webpack-transpiler/src/fs/InputFileSystem.ts (hunk 2 above)
Comment (nicojs) [reply packages/stryker-webpack-transpiler/src/fs/InputFileSystem.ts]: Yes we can!
