### PR TITLE
fix(InputFileResolver): Presume .zip and .tar are binary files.

### LINKED ISSUE #447: Extend binary file extentions list
Hi,

Earlier Me and Nico where trying to use Stryker on an Typescript project. We noticed we had some failing tests. After some debugging we found out our .zip files were correctly interpreted as binary files.

Some additional file extensions would be nice.
`tar`, `zip`

(Sorry for the unclear explanation)

Greets

### PR DESCRIPTION
**Pull request by nicojs**
Fixes #447

### CODE REVIEW

File: packages/stryker/test/unit/InputFileResolverSpec.ts [hunk 1]
```diff
@@ -244,4 +246,22 @@ describe('InputFileResolver', () => {
...
+    sut = new InputFileResolver([], binaryFiles, reporter);
+
+    // Act
+    const actual = await sut.resolve();
+
+    // Assert
+    expect(actual).deep.eq(binaryFiles.map(file => binaryFile({ 
+      name: path.resolve(file), 
+      mutated: false, 
+      transpiled: true
```
Comment (simondel) [inline packages/stryker/test/unit/InputFileResolverSpec.ts]: Why should `transpiled` be true?

Comment (nicojs) [reply packages/stryker/test/unit/InputFileResolverSpec.ts]: Because that is the default when no `transpiled` flag is given. At the same time the default for `binaryFile` is false.

Comment (simondel) [reply packages/stryker/test/unit/InputFileResolverSpec.ts]: > At the same time the default for binaryFile is false.
But you just expect that it's true here.

Comment (nicojs) [reply packages/stryker/test/unit/InputFileResolverSpec.ts]: Yes it should be true. The `InputFileResolver` should set it to true by default, right?
